# Generated by Django 4.1.6 on 2023-02-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author_alter_post_bio_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Kategoriya posteri'),
        ),
        migrations.AddField(
            model_name='post',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.contributor', verbose_name='Kontributor'),
        ),
    ]
